### ISSUE TITLE
wrong date for `goldenticket` command output

### ISSUE THREAD

**Issue by DrorDvash** [yaap7/ldapsearch-ad#14]
Hi, 
The last time the krbtgt password changed presents wrong date:
![image](https://github.com/user-attachments/assets/ea37d4e9-5431-484a-b186-d58cc91ff497)

While the actual value is:
output from powerview.py
![image](https://github.com/user-attachments/assets/9254997e-dc9d-4bc1-82a2-bd62659ef915)

output from bloodhound 
![image](https://github.com/user-attachments/assets/5a912e57-3eed-4ecf-a39b-e6b873e05c63)

**Comment by yaap7** [comment]
Thank you for reporting this error.
A fix is ready to be pushed soon, in the next commit.

**Comment by DrorDvash** [comment]
Checked and verified its working. Thanks for the quick fix :)
![image](https://github.com/user-attachments/assets/501b0e6e-85f2-477e-bed7-753b82ae3698)

Sidenote, not related to the issue:
I saw you pushed the changes, so I did `pipx upgrade ldapsearchad` but nothing changed, the new changes weren't pulled from the github..but uninstall & install helped- only then did the changes take place. any idea why is that?

![image](https://github.com/user-attachments/assets/ab050df3-d7f8-4fdf-9ed3-f8bc58d300ca)

**Comment by yaap7** [comment]
To be honest, I'm confused with python packaging. At first, I learned that `setup.py` was deprecated in favor of `pyproject.toml`, then someone make a push-request to add `setup.py` to enable installation via `pipx`....

But to answer your question, I suppose the upgrade is not working because I didn't increase the version number, so pipx could not know there is new modifications.
I will make a few more improvements, mostly code cleaning, and upgrade the version number to allow future `pipx upgrade`.

Once again, thanks for this report, you help me to learn all those subtleties :)
